# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/15827/OneDrive/bitmips_experiments-master/lab3/single_cycle/single_cycle.srcs/sources_1/new/ip/inst_rom/inst_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_rom || ORIG_REF_NAME==inst_rom} -quiet] -quiet

# XDC: c:/Users/15827/OneDrive/bitmips_experiments-master/lab3/single_cycle/single_cycle.srcs/sources_1/new/ip/inst_rom/inst_rom_ooc.xdc
